import assert from "node:assert/strict";
import { chmod, mkdtemp, mkdir, readFile, utimes, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import test from "node:test";

const repoRoot = path.resolve(import.meta.dirname, "..");
const verifier = path.join(repoRoot, "scripts", "verify-release.mjs");
const tauriConfigPath = path.join(repoRoot, "src-tauri", "tauri.conf.json");
const ciWorkflowPath = path.join(repoRoot, ".github", "workflows", "ci.yml");
const releaseWorkflowPath = path.join(repoRoot, ".github", "workflows", "release.yml");
const releaseCandidatePath = path.join(repoRoot, "docs", "release-candidate.md");
const readmePath = path.join(repoRoot, "README.md");
const packageJsonPath = path.join(repoRoot, "package.json");
const dmgPackagerPath = path.join(repoRoot, "scripts", "package-macos-dmg.mjs");
const brandedAppBundleName = "SpielGantt.app";
const brandedDmgName = "SpielGantt_1.0.0-rc.1_aarch64.dmg";

function runVerifier(appPath) {
  return runVerifierWithArgs([
    "--app",
    appPath,
    "--dmg",
    path.join(path.dirname(appPath), brandedDmgName),
  ]);
}

function runVerifierWithArgs(args) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [verifier, ...args], {
      cwd: repoRoot,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("close", (status) => resolve({ status, stdout, stderr }));
  });
}

function runDmgPackagerWithArgs(args) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [dmgPackagerPath, ...args], {
      cwd: repoRoot,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("close", (status) => resolve({ status, stdout, stderr }));
  });
}

const agentTemplateFiles = [
  "AGENTS.md",
  ".agents/skills/use-spielgantt/SKILL.md",
  ".agents/skills/setup-spielgantt/SKILL.md",
  ".agents/skills/update-spielgantt/SKILL.md",
  ".agents/skills/review-spielgantt/SKILL.md",
];

async function writeFakeAgentTemplates(appPath) {
  const templatesRoot = path.join(appPath, "Contents", "Resources", "agent-templates");
  for (const relativePath of agentTemplateFiles) {
    const templatePath = path.join(templatesRoot, relativePath);
    await mkdir(path.dirname(templatePath), { recursive: true });
    await writeFile(
      templatePath,
      `Generated by SpielGantt agent scaffolding\n${relativePath}\n`,
    );
  }
}

async function writeFakeAgentCli(appPath) {
  const cliPath = path.join(appPath, "Contents", "MacOS", "spielgantt");
  await writeFile(
    cliPath,
    `#!/usr/bin/env node
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const args = process.argv.slice(2);
const cliPath = process.argv[1];
const appPath = path.resolve(path.dirname(cliPath), "..", "..");

function prepare(projectPath) {
  mkdirSync(path.join(projectPath, ".spielgantt"), { recursive: true });
  writeFileSync(path.join(projectPath, "AGENTS.md"), "Generated by SpielGantt agent scaffolding\\n");
  for (const skill of ["use-spielgantt", "setup-spielgantt", "update-spielgantt", "review-spielgantt"]) {
    const skillPath = path.join(projectPath, ".agents", "skills", skill, "SKILL.md");
    mkdirSync(path.dirname(skillPath), { recursive: true });
    writeFileSync(skillPath, "Generated by SpielGantt agent scaffolding\\n");
  }
  writeFileSync(
    path.join(projectPath, ".spielgantt", "agent.json"),
    JSON.stringify({ schema_version: 1, cli_path: cliPath, version: "1.0.0-rc.1" }, null, 2) + "\\n",
  );
}

if (args.join(" ") === "agent runtime --json") {
  console.log(JSON.stringify({
    version: "1.0.0-rc.1",
    executable_path: cliPath,
    package_context: {
      platform: "macos",
      kind: "macos_app_bundle",
      package_path: appPath,
    },
  }));
} else if (args[0] === "init") {
  const projectPath = args[1];
  mkdirSync(path.join(projectPath, ".spielgantt"), { recursive: true });
  writeFileSync(
    path.join(projectPath, ".spielgantt", "project.json"),
    JSON.stringify({ schema_version: 1, folder_naming: "task_id" }, null, 2) + "\\n",
  );
  prepare(projectPath);
  console.log(\`Initialized SpielGantt project in \${projectPath}\`);
} else if (args[0] === "agent" && args[1] === "prepare" && args[2] === "--json") {
  const projectPath = args[3];
  prepare(projectPath);
  console.log(JSON.stringify({
    project_root: projectPath,
    outcome: "unchanged",
    files: [],
    agent: {
      ready: true,
      agents_md_present: true,
      skills_dir_present: true,
      metadata_present: true,
      recorded_cli_path: cliPath,
    },
  }));
} else {
  console.error(\`unsupported fake CLI args: \${args.join(" ")}\`);
  process.exit(1);
}
`,
  );
  await chmod(cliPath, 0o755);
}

async function makeAppBundle(options = {}) {
  const {
    runnableAgentCli = true,
    agentTemplates = true,
    appBundleName = brandedAppBundleName,
    dmgArtifact = true,
  } = options;
  const root = await mkdtemp(path.join(tmpdir(), "spielgantt-release-test-"));
  const appPath = path.join(root, appBundleName);
  await mkdir(path.join(appPath, "Contents", "MacOS"), { recursive: true });
  await mkdir(path.join(appPath, "Contents", "Resources"), { recursive: true });
  await writeFile(
    path.join(appPath, "Contents", "Info.plist"),
    "<plist><dict><key>CFBundleName</key><string>SpielGantt</string></dict></plist>\n",
  );
  if (runnableAgentCli) {
    await writeFakeAgentCli(appPath);
  } else {
    await writeFile(path.join(appPath, "Contents", "MacOS", "spielgantt"), "");
  }
  if (agentTemplates) {
    await writeFakeAgentTemplates(appPath);
  }
  if (dmgArtifact) {
    await writeFile(path.join(root, brandedDmgName), "fake dmg\n");
  }
  return appPath;
}

test("Tauri config brands the desktop app as SpielGantt", async () => {
  const config = JSON.parse(await readFile(tauriConfigPath, "utf8"));

  assert.equal(config.productName, "SpielGantt");
  assert.equal(config.app.windows[0].title, "SpielGantt");
});

test("Tauri config builds the macOS app bundle used by the DMG installer", async () => {
  const config = JSON.parse(await readFile(tauriConfigPath, "utf8"));

  assert.deepEqual(config.bundle.targets, ["app"]);
});

test("macOS DMG packager stages the app with an Applications shortcut", async () => {
  const appPath = await makeAppBundle();
  const outputPath = path.join(path.dirname(appPath), brandedDmgName);

  const result = await runDmgPackagerWithArgs([
    "--app",
    appPath,
    "--output",
    outputPath,
    "--dry-run",
  ]);

  assert.equal(result.status, 0, result.stderr);
  const plan = JSON.parse(result.stdout);
  assert.equal(plan.appPath, appPath);
  assert.equal(plan.outputPath, outputPath);
  assert.deepEqual(plan.contents, [brandedAppBundleName, "Applications"]);
  assert.equal(plan.applicationsShortcutTarget, "/Applications");
});

test("GitHub release infrastructure runs the MVP gate from a clean checkout", async () => {
  const ciWorkflow = await readFile(ciWorkflowPath, "utf8");
  const releaseWorkflow = await readFile(releaseWorkflowPath, "utf8");
  const releaseCandidate = await readFile(releaseCandidatePath, "utf8");
  const readme = await readFile(readmePath, "utf8");

  for (const command of [
    "npm ci",
    "npm run test:frontend",
    "npm run test:release",
    "npm run build",
    "cargo test --manifest-path src-tauri/Cargo.toml",
    "cargo build --release --manifest-path src-tauri/Cargo.toml --bin spielgantt",
  ]) {
    assert.match(ciWorkflow, new RegExp(command.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }

  assert.match(ciWorkflow, /npm run test:architecture/);
  assert.match(releaseWorkflow, /on:\s*\n\s*push:\s*\n\s*tags:/);
  assert.match(releaseWorkflow, /npm ci/);
  assert.match(releaseWorkflow, /npm run tauri -- build/);
  assert.match(releaseWorkflow, /npm run release:dmg/);
  assert.match(releaseWorkflow, /npm run release:verify/);
  assert.match(releaseWorkflow, /SpielGantt\.app/);
  assert.match(releaseWorkflow, /SpielGantt_.*\.dmg/);
  assert.match(releaseWorkflow, /if-no-files-found:\s*error/);
  assert.match(releaseWorkflow, /actions\/upload-artifact/);
  assert.match(releaseWorkflow, /softprops\/action-gh-release/);
  assert.match(releaseCandidate, /DMG/i);
  assert.match(releaseCandidate, /macOS DMG is the only production GUI installer/i);
  assert.match(releaseCandidate, /contents: write/i);
  assert.match(readme, /tagged pushes matching\s+`v\*`/i);
  assert.match(readme, /SpielGantt_.*\.dmg/i);
  assert.match(readme, /contents: write/i);
});

test("fresh release command builds the current source before verification", async () => {
  const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8"));
  const releaseBuild = packageJson.scripts["release:build"];
  const readme = await readFile(readmePath, "utf8");

  assert.match(releaseBuild, /npm run build/);
  assert.match(
    releaseBuild,
    /cargo build --release --manifest-path src-tauri\/Cargo\.toml --bin spielgantt/,
  );
  assert.match(releaseBuild, /npm run tauri -- build/);
  assert.match(releaseBuild, /npm run release:dmg/);
  assert.match(releaseBuild, /npm run release:verify/);
  assert.ok(
    releaseBuild.indexOf("npm run build") < releaseBuild.indexOf("npm run release:verify"),
    "frontend build must happen before verification",
  );
  assert.ok(
    releaseBuild.indexOf("cargo build --release") < releaseBuild.indexOf("npm run release:verify"),
    "release CLI build must happen before verification",
  );
  assert.ok(
    releaseBuild.indexOf("npm run tauri -- build") < releaseBuild.indexOf("npm run release:verify"),
    "Tauri bundle build must happen before verification",
  );
  assert.ok(
    releaseBuild.indexOf("npm run release:dmg") < releaseBuild.indexOf("npm run release:verify"),
    "DMG packaging must happen before verification",
  );
  assert.match(readme, /npm run release:build/);
});

test("release verification accepts a clean macOS app bundle", async () => {
  const appPath = await makeAppBundle();

  const result = await runVerifier(appPath);

  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /Verified architecture guard/);
  assert.match(result.stdout, /Verified app bundle/);
  assert.match(result.stdout, /Verified macOS DMG artifact/);
  assert.match(result.stdout, /SpielGantt\.app/);
  assert.match(result.stdout, /SpielGantt_.*\.dmg/);
});

test("release verification rejects a missing macOS DMG artifact", async () => {
  const appPath = await makeAppBundle({ dmgArtifact: false });

  const result = await runVerifier(appPath);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /DMG artifact/i);
  assert.match(result.stderr, /does not exist/i);
});

test("release verification rejects a stale app bundle", async () => {
  const appPath = await makeAppBundle();
  const staleTime = new Date("2000-01-01T00:00:00Z");
  await utimes(appPath, staleTime, staleTime);

  const result = await runVerifier(appPath);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /stale/i);
  assert.match(result.stderr, /npm run release:build/);
});

test("release verification rejects an app bundle without a runnable agent CLI", async () => {
  const appPath = await makeAppBundle({ runnableAgentCli: false });

  const result = await runVerifier(appPath);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /agent CLI/i);
});

test("release verification rejects test fixtures and local-only paths in the app bundle", async () => {
  const appPath = await makeAppBundle();
  await mkdir(path.join(appPath, "Contents", "Resources", "fixtures"), {
    recursive: true,
  });
  await writeFile(
    path.join(appPath, "Contents", "Resources", "fixtures", "sample.txt"),
    "source: /Users/alice/SpielGantt\n",
  );

  const result = await runVerifier(appPath);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /fixtures/);
  assert.match(result.stderr, /local-only path/);
});

test("release verification rejects a release candidate without documented known limitations", async () => {
  const appPath = await makeAppBundle();
  const missingNotes = path.join(path.dirname(appPath), "missing-release-notes.md");

  const result = await runVerifierWithArgs([
    "--app",
    appPath,
    "--dmg",
    path.join(path.dirname(appPath), brandedDmgName),
    "--release-notes",
    missingNotes,
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /known limitations/i);
  assert.match(result.stderr, /missing-release-notes\.md/);
});
