use serde_json::Value;
use tempfile::tempdir;

mod support;

#[test]
fn agent_prepare_json_creates_project_agent_scaffolding() {
    let workspace_dir = tempdir().expect("temporary directory should be created");
    let project_dir = support::create_unprepared_project(workspace_dir.path(), "project");
    let canonical_project_dir =
        std::fs::canonicalize(&project_dir).expect("project directory should canonicalize");

    let prepare_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        prepare_output.status.success(),
        "agent prepare --json should succeed: {prepare_output:?}"
    );
    assert!(
        support::stderr_text(&prepare_output).is_empty(),
        "agent prepare --json should keep diagnostics out of stdout JSON"
    );

    let prepared: Value = serde_json::from_str(&support::stdout_text(&prepare_output))
        .expect("agent prepare --json stdout should be valid JSON");
    assert_eq!(prepared["schema_version"], 1);
    assert_eq!(
        prepared["project_root"],
        canonical_project_dir.display().to_string()
    );
    assert_eq!(prepared["outcome"], "created");
    assert_eq!(prepared["agent"]["ready"], true);
    assert_eq!(
        prepared["agent"]["recorded_cli_path"],
        env!("CARGO_BIN_EXE_spielgantt")
    );

    assert!(
        project_dir.join("AGENTS.md").is_file(),
        "agent prepare should write project AGENTS.md"
    );
    let project_guidance = std::fs::read_to_string(project_dir.join("AGENTS.md"))
        .expect("generated AGENTS.md should be readable");
    assert!(
        project_guidance.contains("Generated by SpielGantt agent scaffolding"),
        "generated AGENTS.md should carry the managed-file marker"
    );
    for skill_name in [
        "review-spielgantt",
        "setup-spielgantt",
        "update-spielgantt",
        "use-spielgantt",
    ] {
        assert!(
            project_dir
                .join(".agents/skills")
                .join(skill_name)
                .join("SKILL.md")
                .is_file(),
            "agent prepare should write the {skill_name} project-local skill"
        );
        let skill = std::fs::read_to_string(
            project_dir
                .join(".agents/skills")
                .join(skill_name)
                .join("SKILL.md"),
        )
        .expect("generated project-local skill should be readable");
        assert!(
            skill.contains("Generated by SpielGantt agent scaffolding"),
            "generated {skill_name} skill should carry the managed-file marker"
        );
    }

    let metadata = std::fs::read_to_string(project_dir.join(".spielgantt/agent.json"))
        .expect("agent prepare should write local agent metadata");
    let metadata: serde_json::Value =
        serde_json::from_str(&metadata).expect("agent metadata should be valid JSON");
    assert_eq!(metadata["schema_version"], 1);
    assert_eq!(metadata["cli_path"], env!("CARGO_BIN_EXE_spielgantt"));
    assert_eq!(metadata["version"], env!("CARGO_PKG_VERSION"));

    let status_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "status", "--json", "project"],
    );
    assert!(
        status_output.status.success(),
        "agent status --json should succeed after preparing scaffolding: {status_output:?}"
    );
    let status: Value = serde_json::from_str(&support::stdout_text(&status_output))
        .expect("agent status --json stdout should be valid JSON");
    assert_eq!(status["schema_version"], 1);
    assert_eq!(status["agent"], prepared["agent"]);
}

#[test]
fn agent_prepare_generates_use_skill_as_the_concrete_cli_reference() {
    let workspace_dir = tempdir().expect("temporary directory should be created");
    let project_dir = support::create_unprepared_project(workspace_dir.path(), "project");

    let prepare_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        prepare_output.status.success(),
        "agent prepare --json should succeed: {prepare_output:?}"
    );

    let use_skill =
        std::fs::read_to_string(project_dir.join(".agents/skills/use-spielgantt/SKILL.md"))
            .expect("generated use skill should be readable");
    for expected_command in [
        "`spielgantt agent snapshot --json [PATH]`",
        "`spielgantt agent prepare --json [PATH]`",
        "`spielgantt agent status --json [PATH]`",
        "`spielgantt validate [--json] [PATH]`",
        "`spielgantt repair [PATH]`",
        "`spielgantt export [PATH]`",
        "`spielgantt task adoptable-folders --json`",
        "`spielgantt task create <TASK_NAME>`",
        "`spielgantt task insert-before <SELECTED_TASK_NAME> <TASK_NAME> --json`",
        "`spielgantt task insert-after <SELECTED_TASK_NAME> <TASK_NAME> --json`",
        "`spielgantt task delete <TASK_NAME> [--remove-from-chart|--delete-directory] [--json]`",
        "`spielgantt task update <TASK_NAME> --status <blocked|unblocked|done>`",
        "`spielgantt task dependency remove <TASK_NAME> <BLOCKER_NAME>`",
        "`spielgantt task relationships --json`",
        "`spielgantt task workflow --json`",
        "`spielgantt event create <EVENT_NAME>`",
        "`spielgantt project update-readme --content <CONTENT> --expected-version <README_VERSION> --json`",
    ] {
        assert!(
            use_skill.contains(expected_command),
            "generated use skill should document {expected_command}: {use_skill}"
        );
    }

    for stale_reference in [
        ".spielgantt/agent.yaml",
        "spielgantt task link",
        "--start-date",
        "--end-date",
        "--progress",
        "task links",
    ] {
        assert!(
            !use_skill.contains(stale_reference),
            "generated use skill should not document stale CLI reference {stale_reference:?}: {use_skill}"
        );
    }

    assert!(
        use_skill.contains(".spielgantt/agent.json"),
        "generated use skill should document current agent metadata path: {use_skill}"
    );
}

#[test]
fn agent_prepare_generates_setup_workflow_for_common_folder_states() {
    let workspace_dir = tempdir().expect("temporary directory should be created");
    let project_dir = support::create_unprepared_project(workspace_dir.path(), "project");

    let prepare_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        prepare_output.status.success(),
        "agent prepare --json should succeed: {prepare_output:?}"
    );

    let setup_skill =
        std::fs::read_to_string(project_dir.join(".agents/skills/setup-spielgantt/SKILL.md"))
            .expect("generated setup skill should be readable");

    for expected_guidance in [
        "Use `use-spielgantt`",
        "empty folder",
        "existing non-SpielGantt folder",
        "existing SpielGantt project",
        "Instantiate",
        "Task folders are buckets",
        "Events do not have folders",
        "CLI calls",
        "Validate",
        "summarize",
    ] {
        assert!(
            setup_skill.contains(expected_guidance),
            "generated setup skill should include guidance for {expected_guidance:?}:\n{setup_skill}"
        );
    }
}

#[test]
fn agent_prepare_generates_update_workflow_for_existing_project_revisions() {
    let workspace_dir = tempdir().expect("temporary directory should be created");
    let project_dir = support::create_unprepared_project(workspace_dir.path(), "project");

    let prepare_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        prepare_output.status.success(),
        "agent prepare --json should succeed: {prepare_output:?}"
    );

    let update_skill =
        std::fs::read_to_string(project_dir.join(".agents/skills/update-spielgantt/SKILL.md"))
            .expect("generated update skill should be readable");

    for expected_guidance in [
        "Use `use-spielgantt`",
        "agent snapshot",
        "clarifying questions",
        "Preview",
        "Add tasks",
        "Rename tasks",
        "Revise task metadata",
        "Add events",
        "Rename events",
        "Revise event usage",
        "dependencies",
        "event endpoints",
        "Preserve user files outside `.spielgantt/`",
        "Treat `.spielgantt/` as managed metadata",
        "Validate",
        "summarize",
    ] {
        assert!(
            update_skill.contains(expected_guidance),
            "generated update skill should include guidance for {expected_guidance:?}:\n{update_skill}"
        );
    }
}

#[test]
fn agent_prepare_generates_safe_review_and_repair_workflow() {
    let workspace_dir = tempdir().expect("temporary directory should be created");
    let project_dir = support::create_unprepared_project(workspace_dir.path(), "project");

    let prepare_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        prepare_output.status.success(),
        "agent prepare --json should succeed: {prepare_output:?}"
    );

    let review_skill =
        std::fs::read_to_string(project_dir.join(".agents/skills/review-spielgantt/SKILL.md"))
            .expect("generated review skill should be readable");

    for expected_guidance in [
        "Use `use-spielgantt`",
        "read-only",
        "snapshot",
        "validation",
        "repair report",
        "export",
        "propose repairs",
        "explicit user decision",
        "Do not mutate",
        "summarize",
    ] {
        assert!(
            review_skill.contains(expected_guidance),
            "generated review skill should include guidance for {expected_guidance:?}:\n{review_skill}"
        );
    }

    assert!(
        !review_skill.contains("`spielgantt "),
        "review workflow should delegate concrete CLI syntax to use-spielgantt:\n{review_skill}"
    );
}

#[test]
fn agent_prepare_refreshes_managed_files_without_removing_user_files() {
    let workspace_dir = tempdir().expect("temporary directory should be created");
    let project_dir = support::create_unprepared_project(workspace_dir.path(), "project");

    let first_prepare = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        first_prepare.status.success(),
        "initial agent prepare should succeed: {first_prepare:?}"
    );

    std::fs::write(project_dir.join("notes.txt"), "ordinary project notes")
        .expect("ordinary user file should be created");
    std::fs::create_dir_all(project_dir.join(".agents/skills/custom-skill"))
        .expect("extra user skill directory should be created");
    std::fs::write(
        project_dir.join(".agents/skills/custom-skill/SKILL.md"),
        "user-owned skill",
    )
    .expect("extra user skill should be written");
    let managed_agents = std::fs::read_to_string(project_dir.join("AGENTS.md"))
        .expect("managed guidance should be readable before refresh");
    std::fs::write(
        project_dir.join("AGENTS.md"),
        managed_agents.replace(
            "# SpielGantt Project Agent Instructions",
            "# Stale SpielGantt Project Agent Instructions",
        ),
    )
    .expect("managed guidance should be changed before refresh");

    let refresh_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        refresh_output.status.success(),
        "agent prepare should refresh managed files: {refresh_output:?}"
    );
    let refresh: Value = serde_json::from_str(&support::stdout_text(&refresh_output))
        .expect("agent prepare refresh stdout should be valid JSON");
    assert_eq!(refresh["outcome"], "refreshed");

    let refreshed_agents = std::fs::read_to_string(project_dir.join("AGENTS.md"))
        .expect("refreshed AGENTS.md should be readable");
    assert!(
        refreshed_agents.contains("# SpielGantt Project Agent Instructions"),
        "agent prepare should refresh managed project guidance"
    );
    assert_eq!(
        std::fs::read_to_string(project_dir.join("notes.txt"))
            .expect("ordinary user file should remain readable"),
        "ordinary project notes"
    );
    assert_eq!(
        std::fs::read_to_string(project_dir.join(".agents/skills/custom-skill/SKILL.md"))
            .expect("extra user skill should remain readable"),
        "user-owned skill"
    );

    let unchanged_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        unchanged_output.status.success(),
        "agent prepare should remain idempotent after refresh: {unchanged_output:?}"
    );
    let unchanged: Value = serde_json::from_str(&support::stdout_text(&unchanged_output))
        .expect("unchanged agent prepare stdout should be valid JSON");
    assert_eq!(unchanged["outcome"], "unchanged");
}

#[test]
fn agent_prepare_refuses_to_overwrite_preexisting_user_agents_file() {
    let workspace_dir = tempdir().expect("temporary directory should be created");
    let project_dir = support::create_unprepared_project(workspace_dir.path(), "project");
    std::fs::write(
        project_dir.join("AGENTS.md"),
        "user-owned project instructions",
    )
    .expect("preexisting user AGENTS.md should be written");

    let prepare_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        !prepare_output.status.success(),
        "agent prepare should fail instead of overwriting user AGENTS.md: {prepare_output:?}"
    );
    assert!(
        support::stdout_text(&prepare_output).is_empty(),
        "failed JSON prepare should not emit a partial JSON report"
    );
    assert!(
        support::stderr_text(&prepare_output).contains("refusing to overwrite"),
        "agent prepare should explain the unmanaged file conflict: {prepare_output:?}"
    );
    assert_eq!(
        std::fs::read_to_string(project_dir.join("AGENTS.md"))
            .expect("preexisting user AGENTS.md should remain readable"),
        "user-owned project instructions"
    );
    assert!(
        !project_dir.join(".agents").exists(),
        "agent prepare should not partially create skills after an AGENTS.md conflict"
    );
    assert!(
        !project_dir.join(".spielgantt/agent.json").exists(),
        "agent prepare should not write metadata after an AGENTS.md conflict"
    );
}

#[test]
fn agent_prepare_refuses_to_overwrite_preexisting_same_named_user_skill() {
    let workspace_dir = tempdir().expect("temporary directory should be created");
    let project_dir = support::create_unprepared_project(workspace_dir.path(), "project");
    let user_skill = project_dir.join(".agents/skills/use-spielgantt/SKILL.md");
    std::fs::create_dir_all(
        user_skill
            .parent()
            .expect("skill path should have a parent"),
    )
    .expect("preexisting user skill directory should be created");
    std::fs::write(&user_skill, "user-owned use-spielgantt guidance")
        .expect("preexisting same-named user skill should be written");

    let prepare_output = support::run_spielgantt_in(
        workspace_dir.path(),
        &["agent", "prepare", "--json", "project"],
    );
    assert!(
        !prepare_output.status.success(),
        "agent prepare should fail instead of overwriting same-named user skill: {prepare_output:?}"
    );
    assert!(
        support::stderr_text(&prepare_output).contains("refusing to overwrite"),
        "agent prepare should explain the unmanaged skill conflict: {prepare_output:?}"
    );
    assert_eq!(
        std::fs::read_to_string(&user_skill)
            .expect("preexisting same-named user skill should remain readable"),
        "user-owned use-spielgantt guidance"
    );
    assert!(
        !project_dir.join("AGENTS.md").exists(),
        "agent prepare should not partially write AGENTS.md after a skill conflict"
    );
    assert!(
        !project_dir.join(".spielgantt/agent.json").exists(),
        "agent prepare should not write metadata after a skill conflict"
    );
}
