use serde::{Deserialize, Serialize};
use std::{
    fmt,
    path::{Path, PathBuf},
};

use crate::{
    project,
    runtime::{self, RuntimeInfo},
};

const AGENTS_MD: &str = include_str!("../agent-templates/AGENTS.md");
const USE_SPIELGANTT_SKILL: &str =
    include_str!("../agent-templates/.agents/skills/use-spielgantt/SKILL.md");
const SETUP_SPIELGANTT_SKILL: &str =
    include_str!("../agent-templates/.agents/skills/setup-spielgantt/SKILL.md");
const UPDATE_SPIELGANTT_SKILL: &str =
    include_str!("../agent-templates/.agents/skills/update-spielgantt/SKILL.md");
const REVIEW_SPIELGANTT_SKILL: &str =
    include_str!("../agent-templates/.agents/skills/review-spielgantt/SKILL.md");
const GENERATED_MARKER: &str = "Generated by SpielGantt agent scaffolding";
pub const REQUIRED_AGENT_SKILL_FILES: [&str; 4] = [
    ".agents/skills/use-spielgantt/SKILL.md",
    ".agents/skills/setup-spielgantt/SKILL.md",
    ".agents/skills/update-spielgantt/SKILL.md",
    ".agents/skills/review-spielgantt/SKILL.md",
];

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct PrepareAgentScaffoldReport {
    project_root: String,
    outcome: PrepareAgentScaffoldOutcome,
    files: Vec<PreparedAgentFile>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PrepareAgentScaffoldOutcome {
    Created,
    Refreshed,
    Unchanged,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct PreparedAgentFile {
    path: String,
    status: PreparedAgentFileStatus,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentReadinessStatus {
    ready: bool,
    agents_md_present: bool,
    skills_dir_present: bool,
    metadata_present: bool,
    recorded_cli_path: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum PreparedAgentFileStatus {
    Created,
    Refreshed,
    Unchanged,
}

#[derive(Debug, Serialize)]
struct AgentMetadata {
    schema_version: u32,
    cli_path: String,
    version: String,
}

#[derive(Debug, Deserialize)]
struct AgentMetadataJson {
    cli_path: Option<String>,
}

struct ManagedAgentFile<'a> {
    relative_path: &'static str,
    contents: &'a str,
    require_generated_marker: bool,
}

impl PrepareAgentScaffoldReport {
    pub fn project_root(&self) -> &str {
        &self.project_root
    }

    pub fn outcome(&self) -> PrepareAgentScaffoldOutcome {
        self.outcome
    }

    pub fn files(&self) -> &[PreparedAgentFile] {
        &self.files
    }
}

impl PreparedAgentFile {
    pub fn path(&self) -> &str {
        &self.path
    }

    pub fn status(&self) -> PreparedAgentFileStatus {
        self.status
    }
}

impl AgentReadinessStatus {
    pub fn ready(&self) -> bool {
        self.ready
    }

    pub fn agents_md_present(&self) -> bool {
        self.agents_md_present
    }

    pub fn skills_dir_present(&self) -> bool {
        self.skills_dir_present
    }

    pub fn metadata_present(&self) -> bool {
        self.metadata_present
    }

    pub fn recorded_cli_path(&self) -> Option<&str> {
        self.recorded_cli_path.as_deref()
    }
}

pub fn readiness_status(project_root: &Path) -> AgentReadinessStatus {
    let agents_md_present = project_root.join("AGENTS.md").is_file();
    let skills_dir_present = project_root.join(".agents/skills").is_dir();
    let required_skill_files_present = REQUIRED_AGENT_SKILL_FILES
        .iter()
        .all(|relative_path| project_root.join(relative_path).is_file());
    let metadata_path = project_root.join(".spielgantt/agent.json");
    let metadata_present = metadata_path.is_file();
    let recorded_cli_path = std::fs::read_to_string(&metadata_path)
        .ok()
        .and_then(|contents| serde_json::from_str::<AgentMetadataJson>(&contents).ok())
        .and_then(|metadata| metadata.cli_path);

    AgentReadinessStatus {
        ready: agents_md_present
            && skills_dir_present
            && required_skill_files_present
            && metadata_present
            && recorded_cli_path.is_some(),
        agents_md_present,
        skills_dir_present,
        metadata_present,
        recorded_cli_path,
    }
}

pub fn not_ready_status() -> AgentReadinessStatus {
    AgentReadinessStatus {
        ready: false,
        agents_md_present: false,
        skills_dir_present: false,
        metadata_present: false,
        recorded_cli_path: None,
    }
}

pub fn prepare(
    target: &Path,
    runtime: &RuntimeInfo,
) -> Result<PrepareAgentScaffoldReport, PrepareAgentScaffoldError> {
    let project_root = project::find_root(target)
        .ok_or_else(|| PrepareAgentScaffoldError::ProjectRootNotFound(target.to_path_buf()))?;

    let metadata = AgentMetadata {
        schema_version: 1,
        cli_path: runtime.executable_path().to_string(),
        version: runtime.version().to_string(),
    };
    let metadata_json = serde_json::to_string_pretty(&metadata)
        .map(|contents| format!("{contents}\n"))
        .map_err(PrepareAgentScaffoldError::SerializeMetadata)?;

    let managed_files = [
        ManagedAgentFile {
            relative_path: "AGENTS.md",
            contents: AGENTS_MD,
            require_generated_marker: true,
        },
        ManagedAgentFile {
            relative_path: ".agents/skills/use-spielgantt/SKILL.md",
            contents: USE_SPIELGANTT_SKILL,
            require_generated_marker: true,
        },
        ManagedAgentFile {
            relative_path: ".agents/skills/setup-spielgantt/SKILL.md",
            contents: SETUP_SPIELGANTT_SKILL,
            require_generated_marker: true,
        },
        ManagedAgentFile {
            relative_path: ".agents/skills/update-spielgantt/SKILL.md",
            contents: UPDATE_SPIELGANTT_SKILL,
            require_generated_marker: true,
        },
        ManagedAgentFile {
            relative_path: ".agents/skills/review-spielgantt/SKILL.md",
            contents: REVIEW_SPIELGANTT_SKILL,
            require_generated_marker: true,
        },
        ManagedAgentFile {
            relative_path: ".spielgantt/agent.json",
            contents: metadata_json.as_str(),
            require_generated_marker: false,
        },
    ];

    preflight_managed_file_conflicts(&project_root, &managed_files)?;

    let files = managed_files
        .into_iter()
        .map(|managed_file| {
            let path = project_root.join(managed_file.relative_path);
            write_managed_file(&path, managed_file.contents).map(|status| PreparedAgentFile {
                path: managed_file.relative_path.to_string(),
                status,
            })
        })
        .collect::<Result<Vec<_>, _>>()?;

    let outcome = if files
        .iter()
        .any(|file| file.status == PreparedAgentFileStatus::Refreshed)
    {
        PrepareAgentScaffoldOutcome::Refreshed
    } else if files
        .iter()
        .any(|file| file.status == PreparedAgentFileStatus::Created)
    {
        PrepareAgentScaffoldOutcome::Created
    } else {
        PrepareAgentScaffoldOutcome::Unchanged
    };

    Ok(PrepareAgentScaffoldReport {
        project_root: project_root.display().to_string(),
        outcome,
        files,
    })
}

pub fn prepare_with_current_runtime(
    target: &Path,
) -> Result<PrepareAgentScaffoldReport, PrepareAgentScaffoldError> {
    let runtime = runtime::current_runtime_info(env!("CARGO_PKG_VERSION"))
        .map_err(PrepareAgentScaffoldError::ResolveRuntime)?;
    prepare(target, &runtime)
}

fn preflight_managed_file_conflicts(
    project_root: &Path,
    managed_files: &[ManagedAgentFile<'_>],
) -> Result<(), PrepareAgentScaffoldError> {
    for managed_file in managed_files {
        if !managed_file.require_generated_marker {
            continue;
        }

        let path = project_root.join(managed_file.relative_path);
        match std::fs::read_to_string(&path) {
            Ok(existing)
                if existing == managed_file.contents || existing.contains(GENERATED_MARKER) => {}
            Ok(_) => {
                return Err(PrepareAgentScaffoldError::UnmanagedFileConflict {
                    path,
                    relative_path: managed_file.relative_path,
                });
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(source) => {
                return Err(PrepareAgentScaffoldError::ReadFile { path, source });
            }
        }
    }

    Ok(())
}

fn write_managed_file(
    path: &Path,
    contents: &str,
) -> Result<PreparedAgentFileStatus, PrepareAgentScaffoldError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|source| {
            PrepareAgentScaffoldError::CreateDirectory {
                path: parent.to_path_buf(),
                source,
            }
        })?;
    }

    match std::fs::read_to_string(path) {
        Ok(existing) if existing == contents => Ok(PreparedAgentFileStatus::Unchanged),
        Ok(_) => {
            std::fs::write(path, contents).map_err(|source| {
                PrepareAgentScaffoldError::WriteFile {
                    path: path.to_path_buf(),
                    source,
                }
            })?;
            Ok(PreparedAgentFileStatus::Refreshed)
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            std::fs::write(path, contents).map_err(|source| {
                PrepareAgentScaffoldError::WriteFile {
                    path: path.to_path_buf(),
                    source,
                }
            })?;
            Ok(PreparedAgentFileStatus::Created)
        }
        Err(source) => Err(PrepareAgentScaffoldError::ReadFile {
            path: path.to_path_buf(),
            source,
        }),
    }
}

#[derive(Debug)]
pub enum PrepareAgentScaffoldError {
    ResolveRuntime(runtime::RuntimeInfoError),
    ProjectRootNotFound(PathBuf),
    SerializeMetadata(serde_json::Error),
    UnmanagedFileConflict {
        path: PathBuf,
        relative_path: &'static str,
    },
    CreateDirectory {
        path: PathBuf,
        source: std::io::Error,
    },
    ReadFile {
        path: PathBuf,
        source: std::io::Error,
    },
    WriteFile {
        path: PathBuf,
        source: std::io::Error,
    },
}

impl fmt::Display for PrepareAgentScaffoldError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ResolveRuntime(source) => {
                write!(formatter, "{source}")
            }
            Self::ProjectRootNotFound(path) => {
                write!(
                    formatter,
                    "could not find a SpielGantt project root at or above '{}'",
                    path.display()
                )
            }
            Self::SerializeMetadata(source) => {
                write!(formatter, "failed to serialize agent metadata: {source}")
            }
            Self::UnmanagedFileConflict {
                path,
                relative_path,
            } => {
                write!(
                    formatter,
                    "refusing to overwrite existing unmarked agent scaffold file '{}' at '{}'",
                    relative_path,
                    path.display()
                )
            }
            Self::CreateDirectory { path, source } => {
                write!(
                    formatter,
                    "failed to create agent scaffold directory '{}': {source}",
                    path.display()
                )
            }
            Self::ReadFile { path, source } => {
                write!(
                    formatter,
                    "failed to read agent scaffold file '{}': {source}",
                    path.display()
                )
            }
            Self::WriteFile { path, source } => {
                write!(
                    formatter,
                    "failed to write agent scaffold file '{}': {source}",
                    path.display()
                )
            }
        }
    }
}

impl std::error::Error for PrepareAgentScaffoldError {}
